
version: '3.8'

services:
  chatters:
    build: .
    container_name: chatters
    restart: unless-stopped
    ports:
      - "8080:8080"  # HTTP server
      - "9090:9090"  # Metrics endpoint
    environment:
      - GIN_MODE=release
      - TZ=Europe/Moscow
    networks:
      - chatters-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9091:9090"  # Prometheus UI
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - chatters-network
    depends_on:
      chatters:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "9900:9900"  # Grafana UI
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - chatters-network
    depends_on:
      - prometheus

networks:
  chatters-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
